version: '{build}'

image: Visual Studio 2019
configuration: Release

before_build:
- dotnet restore

build:
  verbosity: minimal

after_test:
- choco install codecov && codecov -f "LockFile.Tests/bin/%CONFIGURATION%/Coverage.xml" --required

artifacts:
- path: LockFile/bin/$(configuration)/LockFile*.nupkg
  name: LockFile.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 5VyEaGo5gRLr9HdkRFqS1enRq+K8Qarg1dzU33CE1dOmVXp43JaS2PQTNgsRHXkc
  artifact: LockFile.nupkg
  on:
    branch: master
    appveyor_repo_tag: true